language: node_js

node_js:
  - 'stable'

# Use container-based Travis infrastructure.
sudo: false

cache:
  directories:
    - node_modules

notifications:
  email: true
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

script: "gulp coverage"